FROM tomcat

COPY server.xml /usr/local/tomcat/conf/server.xml
COPY manager.xml /usr/local/tomcat/conf/Catalina/localhost/manager.xml
#COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
