# Refresh 25/01/2024
name: Docker (Daily)

# 03:30 daily
on:
  schedule:
    - cron: '30 03 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action

      # httpd-tls/rocky8
      - name: build/push (httpd-tls/rocky8)
        uses: docker/build-push-action@v3
        with:
          context: httpd-tls/rocky8
          platforms: linux/amd64
          push: true
          tags: ghcr.io/cropgeeks/httpd-tls:rocky8
      
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
